import { Link } from "react-router-dom";
import { SkillCard } from "../skills-ui/skill-card";
import { ReactNode } from "react";

interface Props {
  title?: ReactNode | string;
  id?: string;
}
export const skills = [
  {
    id: "1",
    name: "Adebayo Cooling",
    title: "Top artisan",
    description: "I will install your sinks and water closet professionally",
    rating: 5.0,
    reviews: 3,
    avatar: "https://i.pravatar.cc/150?img=32",
    cover: "https://picsum.photos/seed/adebayo/600/400",
    email: "adeocool@gmail.com",
    phone: "09011922193",
    response_time: "1 hour",
    extra_services: 3,
    category: "Plumbing",
    location: "KANO",
    status: "Away",
  },
  {
    id: "2",
    name: "Chinedu Fixit",
    title: "Expert Technician",
    description: "Professional AC installation and servicing for homes.",
    rating: 4.8,
    reviews: 12,
    avatar: "https://i.pravatar.cc/150?img=76",
    cover: "https://picsum.photos/seed/chinedu/600/400",
    email: "chinedu.fixit@gmail.com",
    phone: "08023456789",
    response_time: "2 hours",
    extra_services: 5,
    category: "Air Conditioning",
    location: "LAGOS",
    status: "Available",
  },
  {
    id: "3",
    name: "Grace Interiors",
    title: "Creative Designer",
    description: "Transform your living spaces with modern interior designs.",
    rating: 4.9,
    reviews: 8,
    avatar: "https://i.pravatar.cc/150?img=45",
    cover: "https://picsum.photos/seed/grace/600/400",
    email: "grace.designs@gmail.com",
    phone: "08198765432",
    response_time: "30 mins",
    extra_services: 2,
    category: "Interior Design",
    location: "ABUJA",
    status: "Available",
  },
  {
    id: "4",
    name: "Ibrahim Wiring",
    title: "Certified Electrician",
    description: "Safe and reliable electrical installations and repairs.",
    rating: 4.7,
    reviews: 15,
    avatar: "https://i.pravatar.cc/150?img=12",
    cover: "https://picsum.photos/seed/ibrahim/600/400",
    email: "ibrahimwire@gmail.com",
    phone: "08134567890",
    response_time: "45 mins",
    extra_services: 4,
    category: "Electrical",
    location: "IBADAN",
    status: "Available",
  },
  {
    id: "5",
    name: "Funmi Paints",
    title: "Master Painter",
    description:
      "Quality painting services for residential and commercial properties.",
    rating: 4.6,
    reviews: 20,
    avatar: "https://i.pravatar.cc/150?img=23",
    cover: "https://picsum.photos/seed/funmi/600/400",
    email: "funmipaints@gmail.com",
    phone: "07056789012",
    response_time: "3 hours",
    extra_services: 3,
    category: "Painting",
    location: "LAGOS",
    status: "Busy",
  },
  {
    id: "6",
    name: "Emeka Builds",
    title: "Construction Specialist",
    description: "Expert bricklaying and building construction services.",
    rating: 4.9,
    reviews: 25,
    avatar: "https://i.pravatar.cc/150?img=33",
    cover: "https://picsum.photos/seed/emeka/600/400",
    email: "emekabuilds@gmail.com",
    phone: "08187654321",
    response_time: "2 hours",
    extra_services: 6,
    category: "Construction",
    location: "ENUGU",
    status: "Available",
  },
  {
    id: "7",
    name: "Aisha Fabrics",
    title: "Fashion Designer",
    description: "Custom tailoring and fashion design for all occasions.",
    rating: 5.0,
    reviews: 18,
    avatar: "https://i.pravatar.cc/150?img=47",
    cover: "https://picsum.photos/seed/aisha/600/400",
    email: "aishafabrics@gmail.com",
    phone: "09023456781",
    response_time: "1 hour",
    extra_services: 4,
    category: "Tailoring",
    location: "ABUJA",
    status: "Available",
  },
  {
    id: "8",
    name: "Tunde Carpentry",
    title: "Woodwork Expert",
    description: "Custom furniture and carpentry services for your home.",
    rating: 4.8,
    reviews: 14,
    avatar: "https://i.pravatar.cc/150?img=68",
    cover: "https://picsum.photos/seed/tunde/600/400",
    email: "tundecarpentry@gmail.com",
    phone: "08145678903",
    response_time: "4 hours",
    extra_services: 5,
    category: "Carpentry",
    location: "LAGOS",
    status: "Available",
  },
  {
    id: "9",
    name: "Blessing Gardens",
    title: "Landscape Designer",
    description: "Beautiful garden designs and maintenance services.",
    rating: 4.7,
    reviews: 9,
    avatar: "https://i.pravatar.cc/150?img=28",
    cover: "https://picsum.photos/seed/blessing/600/400",
    email: "blessinggardens@gmail.com",
    phone: "07034567892",
    response_time: "1 hour",
    extra_services: 3,
    category: "Gardening",
    location: "PORT HARCOURT",
    status: "Available",
  },
  {
    id: "10",
    name: "Yusuf Welding",
    title: "Metal Fabricator",
    description: "Professional welding and metal fabrication services.",
    rating: 4.5,
    reviews: 11,
    avatar: "https://i.pravatar.cc/150?img=51",
    cover: "https://picsum.photos/seed/yusuf/600/400",
    email: "yusufwelding@gmail.com",
    phone: "08156789014",
    response_time: "2 hours",
    extra_services: 2,
    category: "Welding",
    location: "KADUNA",
    status: "Busy",
  },
  {
    id: "11",
    name: "Ngozi Cleaning",
    title: "Professional Cleaner",
    description: "Thorough cleaning services for homes and offices.",
    rating: 4.9,
    reviews: 22,
    avatar: "https://i.pravatar.cc/150?img=38",
    cover: "https://picsum.photos/seed/ngozi/600/400",
    email: "ngozicleaning@gmail.com",
    phone: "09087654323",
    response_time: "30 mins",
    extra_services: 4,
    category: "Cleaning",
    location: "LAGOS",
    status: "Available",
  },
  {
    id: "12",
    name: "Bashir Tiling",
    title: "Tile Expert",
    description: "Professional floor and wall tiling services.",
    rating: 4.6,
    reviews: 16,
    avatar: "https://i.pravatar.cc/150?img=14",
    cover: "https://picsum.photos/seed/bashir/600/400",
    email: "bashirtiling@gmail.com",
    phone: "08123456785",
    response_time: "3 hours",
    extra_services: 3,
    category: "Tiling",
    location: "ABUJA",
    status: "Available",
  },
  {
    id: "13",
    name: "Chioma Beauty",
    title: "Makeup Artist",
    description: "Professional makeup and beauty services for all events.",
    rating: 5.0,
    reviews: 30,
    avatar: "https://i.pravatar.cc/150?img=43",
    cover: "https://picsum.photos/seed/chioma/600/400",
    email: "chiomabeauty@gmail.com",
    phone: "07045678904",
    response_time: "1 hour",
    extra_services: 7,
    category: "Beauty Services",
    location: "LAGOS",
    status: "Available",
  },
  {
    id: "14",
    name: "Musa Roofing",
    title: "Roofing Specialist",
    description: "Expert roofing installation and repair services.",
    rating: 4.7,
    reviews: 13,
    avatar: "https://i.pravatar.cc/150?img=59",
    cover: "https://picsum.photos/seed/musa/600/400",
    email: "musaroofing@gmail.com",
    phone: "08167890125",
    response_time: "2 hours",
    extra_services: 4,
    category: "Roofing",
    location: "JOS",
    status: "Away",
  },
  {
    id: "15",
    name: "Patience Catering",
    title: "Professional Chef",
    description: "Delicious catering services for events and occasions.",
    rating: 4.8,
    reviews: 28,
    avatar: "https://i.pravatar.cc/150?img=26",
    cover: "https://picsum.photos/seed/patience/600/400",
    email: "patiencecatering@gmail.com",
    phone: "09034567896",
    response_time: "4 hours",
    extra_services: 6,
    category: "Catering",
    location: "ABUJA",
    status: "Available",
  },
  {
    id: "16",
    name: "Daniel AutoFix",
    title: "Auto Mechanic",
    description: "Reliable car repairs and maintenance services.",
    rating: 4.6,
    reviews: 19,
    avatar: "https://i.pravatar.cc/150?img=70",
    cover: "https://picsum.photos/seed/daniel/600/400",
    email: "danielautofix@gmail.com",
    phone: "08145678907",
    response_time: "1 hour",
    extra_services: 5,
    category: "Auto Repair",
    location: "LAGOS",
    status: "Busy",
  },
  {
    id: "17",
    name: "Fatima Tech",
    title: "Computer Technician",
    description: "Expert computer repairs and IT support services.",
    rating: 4.9,
    reviews: 24,
    avatar: "https://i.pravatar.cc/150?img=20",
    cover: "https://picsum.photos/seed/fatima/600/400",
    email: "fatimatech@gmail.com",
    phone: "07056789018",
    response_time: "45 mins",
    extra_services: 4,
    category: "IT Support",
    location: "ABUJA",
    status: "Available",
  },
  {
    id: "18",
    name: "Kunle Photography",
    title: "Professional Photographer",
    description: "Capture your special moments with stunning photography.",
    rating: 5.0,
    reviews: 35,
    avatar: "https://i.pravatar.cc/150?img=52",
    cover: "https://picsum.photos/seed/kunle/600/400",
    email: "kunlephoto@gmail.com",
    phone: "08187654329",
    response_time: "2 hours",
    extra_services: 8,
    category: "Photography",
    location: "LAGOS",
    status: "Available",
  },
  {
    id: "19",
    name: "Amaka Events",
    title: "Event Planner",
    description: "Professional event planning and coordination services.",
    rating: 4.8,
    reviews: 21,
    avatar: "https://i.pravatar.cc/150?img=44",
    cover: "https://picsum.photos/seed/amaka/600/400",
    email: "amakaevents@gmail.com",
    phone: "09023456790",
    response_time: "3 hours",
    extra_services: 7,
    category: "Event Planning",
    location: "PORT HARCOURT",
    status: "Available",
  },
  {
    id: "20",
    name: "Segun Security",
    title: "Security Expert",
    description: "CCTV installation and security system setup.",
    rating: 4.7,
    reviews: 17,
    avatar: "https://i.pravatar.cc/150?img=67",
    cover: "https://picsum.photos/seed/segun/600/400",
    email: "segunsecurity@gmail.com",
    phone: "08134567901",
    response_time: "1 hour",
    extra_services: 3,
    category: "Security",
    location: "LAGOS",
    status: "Available",
  },
];

export function Section({ title, id }: Props) {
  return (
    <section id={id || undefined} className="px-1 py-6 md:px-12">
      <div className="">
        {title && (
          <h2 className="mb-3 text-3xl font-extrabold xl:mb-6">{title}</h2>
        )}
        <div className="grid grid-cols-2 gap-2 md:grid-cols-3 lg:gap-4 xl:grid-cols-5">
          {skills.map((skill, index) => (
            <Link to={`/service/${id}`}>
              <SkillCard key={index} skill={skill} />
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
}

export default Section;
